version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run-script build
  
  post_build:
    commands:
      - echo "Deployed to s3"    
artifacts:
   files:
     - '**/*'
