version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  
  post_build:
    commands:
      - aws s3 cp sync /build s3://cicd-react12
